### PR TITLE
Fix notice if comment is not set. Fix announce-list not conforming to spec

### PR DESCRIPTION
**Pull request by renan-s-oliveira**
Replace $this->data['announce-list'] = array_values($announceList); to $this->data['announce-list'] = array_chunk($announceList); resolve announce-list
Replace return $this->data['comment']; to return isset($this->data['comment']); Resolve comment

### CODE REVIEW

**Comment by arokettu** [comment]
The tests are still pending but your getComment will try to return boolean and crash

**Comment by arokettu** [comment]
What's the issue with the announce-list?

**Comment by renan-s-oliveira** [comment]
> The tests are still pending but your getComment will try to return boolean and crash

torrents without comments return Undefined index: comment
my bad, correct is return $this->data['comment'] ?? null;

**Comment by renan-s-oliveira** [comment]
> What's the issue with the announce-list?

https://prnt.sc/v9ajpp

after replace $this->data['announce-list'] = array_chunk($announceList);

https://prnt.sc/v9al45

**Comment by arokettu** [comment]
I see, It's an array of arrays by the spec. Thanks for noticing

however I think it should support this grouping feature so it needs some better handling. But if you don't want to do it, never mind

**Comment by arokettu** [comment]
> my bad, correct is return $this->data['comment'] ?? null;

care to update your MR?

**Comment by arokettu** [comment]
For future reference: these are 2 separate problems, it was a good idea to create 2 separate issues

**Comment by renan-s-oliveira** [comment]
> $ this-> data ['announce-list'] = array_chunk ($ announceList);
correct code I forgot a parameter $ this-> data ['announce-list'] = array_chunk ($ announceList, 1) ; I updated my code

**Comment by arokettu** [comment]
split into #4 and #5

**Pull request closed without merging**
